odadoz/urls.py
# Define urlpatterns in project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views.generic import TemplateView

urlpatterns = (
    [
        path("admin/", admin.site.urls),
        path("", include("web.urls", namespace="web")),
        path("", include("product.urls", namespace="product")),
        path("", include("order.urls", namespace="order")),
        path("sitemap.xml", TemplateView.as_view(template_name="sitemap.xml", content_type="text/xml")),
        path("robots.txt", TemplateView.as_view(template_name="robots.txt", content_type="text/plain")),
        path('accounts/', include('registration.backends.simple.urls')),
    ]
    + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
)

admin.site.site_header = "PROJECT Administration"
admin.site.site_title = "PROJECT Admin Portal"
admin.site.index_title = "Welcome to PROJECT Admin Portal"

order/urls.py
from django.urls import path
from . import views
from .views import wishlist, add_to_wishlist, remove_from_wishlist

app_name = "order"

urlpatterns = [
    #cart
    path('cart/add/<int:id>/', views.cart_add, name='cart_add'),
    path('cart/item_clear/<int:id>/', views.item_clear, name='item_clear'),
    path('cart/item_increment/<int:id>/',
         views.item_increment, name='item_increment'),
    path('cart/item_decrement/<int:id>/',
         views.item_decrement, name='item_decrement'),
    path('cart/cart_clear/', views.cart_clear, name='cart_clear'),
    path('cart/cart-detail/',views.cart_detail,name='cart_detail'),
    path('checkout',views.checkout,name='checkout'),
    # wishlist
    path('wishlist/', wishlist, name='wishlist'),
    path('add_to_wishlist/<int:product_id>/', add_to_wishlist, name='add_to_wishlist'),
    path('remove_from_wishlist/<int:item_id>/', remove_from_wishlist, name='remove_from_wishlist'),
    #account 
    path("account", views.account, name="account"),
    path('order/',views.your_order,name='order'),
    #profile update
    path('profile/',views.profile,name='profile'),
    path('profile/update',views.profile_update,name='profile_update'),
]

product/urls.py
from django.urls import path
from . import views

app_name = "product"

urlpatterns = [
    path("", views.index, name="index"),
    # shop
    path("shop/", views.shop, name="shop"),
    path("shop/filter-data", views.filter_data, name="filter-data"),
    path('shop/<slug:slug>/', views.ShopDetailView.as_view(), name='shop_details'),
]

web/urls.py
from django.urls import path
from . import views

app_name = "web"

urlpatterns = [
    path("contact/", views.contact, name="contact"),
    path("about/", views.about, name="about"),
]

templates/cart/cart.html
{% extends "partials/base.html" %}
{% load static %}
{% load cart_tag %}
{% block title %} Cart {% endblock  %}
{% block content %}
    <!-- body_wrap - start -->
    <div class="body_wrap">

      <!-- backtotop - start -->
      <div class="backtotop">
        <a href="javascript:void(0)" class="scroll">
          <i class="far fa-arrow-up"></i>
        </a>
      </div>
      <!-- backtotop - end -->

      <!-- main body - start
      ================================================== -->
      <main>

        <!-- sidebar cart - start
        ================================================== -->
        <div class="sidebar-menu-wrapper">
          <div class="cart_sidebar">
            <button type="button" class="close_btn"><i class="fal fa-times"></i></button>

            <ul class="cart_items_list ul_li_block mb_30 clearfix">
              {% for key,value in request.session.cart.items %}
              <li>
                <div class="item_image">
                  <img src="{{value.image}}" alt="Getyootech - Gadgets Ecommerce Site Template">
                </div>
                <div class="item_content">
                  <h4 class="item_title">{{value.name}}</h4>
                  <span class="item_price">${{value.price}}</span>
                </div>
                <a href="{% url "order:item_clear" key %}"><button type="button" class="remove_btn"><i class="fal fa-trash-alt"></i></button></a>
              </li>
              {% endfor %}
            </ul>

            <ul class="total_price ul_li_block mb_30 clearfix">
              <li>
                <span>Subtotal:</span>
                <span>${{cart_total_amount}}</span>
              </li>
              <li>
                <span>Vat 5%:</span>
                <span>$4.5</span>
              </li>
              <li>
                <span>Discount 20%:</span>
                <span>- $18.9</span>
              </li>
              <li>
                <span>Total:</span>
                <span>${{cart_total_amount}}</span>
              </li>
            </ul>

            <ul class="btns_group ul_li_block clearfix">
              <li><a class="btn btn_primary" href="{% url "order:cart_detail" %}">View Cart</a></li>
              <li><a class="btn btn_secondary" href="{% url "order:checkout" %}">Checkout</a></li>
            </ul>
          </div>

          <div class="cart_overlay"></div>
        </div>
        <!-- sidebar cart - end
        ================================================== -->

        <!-- breadcrumb_section - start
        ================================================== -->
        <div class="breadcrumb_section">
          <div class="container">
            <ul class="breadcrumb_nav ul_li">
              <li><a href="{% url "product:index" %}">Home</a></li>
              <li><a href="{% url "product:shop" %}">Shop</a></li>

            </ul>
          </div>
        </div>
        <!-- breadcrumb_section - end
        ================================================== -->

        <!-- cart_section - start
        ================================================== -->
        <section class="cart_section section_space">
          <div class="container">
            <div class="cart_update_wrap">
              <p class="mb-0"><i class="fal fa-check-square"></i> Shipping costs updated.</p>
            </div>

            <div class="cart_table">
              <table class="table">
                <thead>
                  <tr>
                    <th>PRODUCT</th>
                    <th class="text-center">PRICE</th>
                    <th class="text-center">QUANTITY</th>
                    <th class="text-center">TOTLA</th>
                    <th class="text-center">REMOVE</th>
                  </tr>
                </thead>
                <tbody>
                  {% for key,value in request.session.cart.items %}
                  <tr id="id{{value.id}}">
                    <td>
                      <div class="cart_product">
                        <img src="{{value.image}}" alt="Getyootech - Gadgets Ecommerce Site Template">
                        <h3><a href="shop_details.html">{{value.name}}</a></h3>
                      </div>
                    </td>
                    <td class="text-center"><span class="price_text">${{value.price}}</span></td>
                    <td class="text-center">
                      <form action="javascript:void(0)">
                        <div class="quantity_input">
                          <a href="{% url 'order:item_decrement' value.product_id %}">
                          <button type="button" class="input_number_decrement">
                            <i class="fal fa-minus"></i>
                          </button>
                          </a>
                          <input class="input_number" type="text" value="{{value.quantity}}">
                          <a href="{% url 'order:item_increment' value.product_id %}">
                          <button type="button" class="input_number_increment">
                            <i class="fal fa-plus"></i>
                          </button>
                          </a>
                        </div>
                      </form>
                    </td>
                    <td class="text-center"><span class="price_text">${{ value.price|multiply:value.quantity }}</span></td>
                    <td class="text-center"><a href="{% url "order:item_clear" key %}"><button type="button" class="remove_btn"><i class="fal fa-trash-alt"></i></button></a></td>
                  </tr>
                  {% endfor %}
                </tbody>
              </table>
            </div>

            <div class="cart_btns_wrap">
              <div class="row">
                <div class="col col-lg-6">

                </div>

                <div class="col col-lg-6">
                  <ul class="btns_group ul_li_right">
                    <li><a class="btn border_black" href="{% url "product:shop" %}">Continue Shopping</a></li>
                    <li><a class="btn border_black" href="{% url "order:cart_clear" %}">Clear Cart</a></li>
                    <li><a class="btn btn_dark" href="{% url "order:checkout" %}">Prceed To Checkout</a></li>
                  </ul>
                </div>
              </div>
            </div>

            <div class="row">
              <div class="col col-lg-6">
                <div class="calculate_shipping">
                 
                </div>
              </div>

              <div class="col col-lg-6">
                <div class="cart_total_table">
                  <h3 class="wrap_title">Cart Totals</h3>
                  <ul class="ul_li_block">
                    <li>
                      <span>Cart Subtotal</span>
                      <span>${{cart_total_amount}}</span>
                    </li>
                    <li>
                      <span>Shipping and Handling</span>
                      <span>Free Shipping</span>
                    </li>
                    <li>
                      <span class="text-danger">Order Total</span>
                      <span class="total_price text-danger">${{cart_total_amount}}</span>
                    </li>
                  </ul>
                </div>
              </div>
            </div>
          </div>
        </section>
        <!-- cart_section - end
        ================================================== -->

        <!-- newsletter_section - start
        ================================================== -->
        <section class="newsletter_section">
          <div class="container">
            <div class="row align-items-center">
              <div class="col col-lg-6">
                <h2 class="newsletter_title text-white">
                  <i class="icofont-paper-plane"></i>
                  Sign Up for Newsletter
                </h2>
              </div>
              <div class="col col-lg-6">
                <form action="javascript:void(0)">
                  <div class="newsletter_form">
                    <input type="email" name="email" placeholder="Enter your email address">
                    <button type="submit" class="btn btn_danger">Submit</button>
                  </div>
                </form>
              </div>
            </div>
          </div>
        </section>
        <!-- newsletter_section - end
        ================================================== -->

      </main>
      <!-- main body - end
      ================================================== -->

    </div>
    <!-- body_wrap - end -->
    {% endblock  %}