odadoz/urls.py
# Define urlpatterns in project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views.generic import TemplateView

urlpatterns = (
    [
        path("admin/", admin.site.urls),
        path("", include("web.urls", namespace="web")),
        path("", include("product.urls", namespace="product")),
        path("", include("order.urls", namespace="order")),
        path("sitemap.xml", TemplateView.as_view(template_name="sitemap.xml", content_type="text/xml")),
        path("robots.txt", TemplateView.as_view(template_name="robots.txt", content_type="text/plain")),
        path('accounts/', include('registration.backends.simple.urls')),
    ]
    + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
)

admin.site.site_header = "PROJECT Administration"
admin.site.site_title = "PROJECT Admin Portal"
admin.site.index_title = "Welcome to PROJECT Admin Portal"

order/urls.py
from django.urls import path
from . import views
from .views import wishlist, add_to_wishlist, remove_from_wishlist

app_name = "order"

urlpatterns = [
    #cart
    path('cart/add/<int:id>/', views.cart_add, name='cart_add'),
    path('cart/item_clear/<int:id>/', views.item_clear, name='item_clear'),
    path('cart/item_increment/<int:id>/',
         views.item_increment, name='item_increment'),
    path('cart/item_decrement/<int:id>/',
         views.item_decrement, name='item_decrement'),
    path('cart/cart_clear/', views.cart_clear, name='cart_clear'),
    path('cart/cart-detail/',views.cart_detail,name='cart_detail'),
    path('checkout',views.checkout,name='checkout'),
    # wishlist
    path('wishlist/', wishlist, name='wishlist'),
    path('add_to_wishlist/<int:product_id>/', add_to_wishlist, name='add_to_wishlist'),
    path('remove_from_wishlist/<int:item_id>/', remove_from_wishlist, name='remove_from_wishlist'),
    #account 
    path("account", views.account, name="account"),
    path('order/',views.your_order,name='order'),
    #profile update
    path('profile/',views.profile,name='profile'),
    path('profile/update',views.profile_update,name='profile_update'),
]

product/urls.py
from django.urls import path
from . import views

app_name = "product"

urlpatterns = [
    path("", views.index, name="index"),
    # shop
    path("shop/", views.shop, name="shop"),
    path("shop/filter-data", views.filter_data, name="filter-data"),
    path('shop/<slug:slug>/', views.ShopDetailView.as_view(), name='shop_details'),
]

web/urls.py
from django.urls import path
from . import views

app_name = "web"

urlpatterns = [
    path("contact/", views.contact, name="contact"),
    path("about/", views.about, name="about"),
]

templates/partials/base.html
{% load static %}
<!doctype html>
<html lang="en">

  <head>

  	<meta charset="utf-8">
  	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  	<meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>{% block title %}{% endblock %}| Odadoz</title>
  	<link rel="shortcut icon" href="{% static 'assets/images/logo/favourite_icon.svg' %}">

  	<!-- fraimwork - css include -->
    <link rel="stylesheet" type="text/css" href="{% static 'assets/css/bootstrap.min.css' %}">

    <!-- icon font - css include -->
    <link rel="stylesheet" type="text/css" href="{% static 'assets/css/fontawesome.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'assets/css/stroke-gap-icons.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'assets/css/icofont.css' %}">

    <!-- animation - css include -->
    <link rel="stylesheet" type="text/css" href="{% static 'assets/css/animate.css' %}">

    <!-- carousel - css include -->
    <link rel="stylesheet" type="text/css" href="{% static 'assets/css/slick.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'assets/css/slick-theme.css' %}">

    <!-- popup - css include -->
    <link rel="stylesheet" type="text/css" href="{% static 'assets/css/magnific-popup.css' %}">

    <!-- jquery-ui - css include -->
    <link rel="stylesheet" type="text/css" href="{% static 'assets/css/jquery-ui.css' %}">

    <!-- select option - css include -->
    <link rel="stylesheet" type="text/css" href="{% static 'assets/css/nice-select.css' %}">

    <!-- custom - css include -->
    <link rel="stylesheet" type="text/css" href="{% static 'assets/css/style.css' %}">

    <!-- script -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>

    <!-- sweetalert -->
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@9.15.3/dist/sweetalert2.all.min.js"></script>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.17.0/font/bootstrap-icons.css">

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>


  </head>


  <body>

    {% include "partials/header.html" %}
    {% block content %}
    
    {% endblock  %}
    {% include "partials/footer.html" %}

    <!-- fraimwork - jquery include -->
    <script src="{% static 'assets/js/jquery.min.js' %}"></script>
    <script src="{% static 'assets/js/popper.min.js' %}"></script>
    <script src="{% static 'assets/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'assets/js/bootstrap5-dropdown-ml-hack.js' %}"></script>

    <!-- carousel - jquery include -->
    <script src="{% static 'assets/js/slick.min.js' %}"></script>

    <!-- popup - jquery include -->
    <script src="{% static 'assets/js/magnific-popup.min.js' %}"></script>

    <!-- jquery-ui - jquery include -->
    <script src="{% static 'assets/js/jquery-ui.js' %}"></script>

    <!-- off canvas sidebar - jquery include -->
    <script src="{% static 'assets/js/mCustomScrollbar.js' %}"></script>

    <!-- select option - jquery include -->
    <script src="{% static 'assets/js/nice-select.min.js' %}"></script>

    <!-- countdown timer - jquery include -->
    <script src="{% static 'assets/js/countdown.js' %}"></script>

    <!-- counter up - jquery include -->
    <script src="{% static 'assets/js/counterup.min.js' %}"></script>
    <script src="{% static 'assets/js/waypoints.min.js' %}"></script>

    <!-- custom - jquery include -->
    <script src="{% static 'assets/js/main.js' %}"></script>
    
    <!-- ajax -->
    <script src="{% static 'assets/js/ajax.js' %}"></script>
    <script src="{% static 'assets/js/cart_wishlist.js' %}"></script>

  </body>
</html>

templates/partials/footer.html
{% load static %}
<!-- footer_section - start
      ================================================== -->
      <footer class="footer_section">
        <div class="footer_widget_area">
          <div class="container">
            <div class="row">
              <div class="col col-lg-4 col-md-6 col-sm-6">
                <div class="footer_widget footer_about">
                  <div class="brand_logo">
                    <a class="brand_link" href="{% url "product:index" %}">
                      <img src="{% static 'assets/images/logo/Odadoz (5).png' %}" alt="Getyootech - Gadgets Ecommerce Site Template">
                    </a>
                  </div>
                  <p>
                    Thank you for choosing Odadoz - Your Ultimate Tech Companion. At Odadoz, we are dedicated to bringing you the latest 
                    in gadgets and cutting-edge technology, ensuring a seamless online shopping experience.
                  </p>
                </div>
              </div>

              <div class="col col-lg-2 col-md-3 col-sm-6">
                <div class="footer_widget footer_useful_links">
                  <h3 class="footer_widget_title text-uppercase">Quick Links</h3>
                  <ul class="ul_li_block">
                    <li><a href="{% url "product:index" %}">HOME</a></li>
                    <li><a href="{% url "web:about" %}">ABOUT</a></li>
                    <li><a href="{% url "product:shop" %}">SHOP</a></li>
                    <li><a href="{% url "web:contact" %}">CONTACT</a></li>
                  </ul>
                </div>
              </div>

              <div class="col col-lg-2 col-md-3 col-sm-6">
                <div class="footer_widget footer_useful_links">
                  <h3 class="footer_widget_title text-uppercase">Custom area</h3>
                  <ul class="ul_li_block">
                    <li><a href="{% url "order:order" %}">Order</a></li>
                    <li><a href="{% url "order:wishlist" %}">Wishlist</a></li>
                    <li><a href="{% url 'order:cart_detail' %}">My Cart</a></li>
                  </ul>
                </div>
              </div>

              <div class="col col-lg-4 col-md-6 col-sm-6">
                <div class="footer_widget footer_contact">
                  <h3 class="footer_widget_title text-uppercase">Contact Onfo</h3>
                  <p>
                    For any inquiries or assistance, feel free to reach out to us:
                  </p>
                </div>
              </div>
            </div>
          </div>
        </div>

        <div class="footer_bottom ">
          <div class="container">
            <div class="row align-items-center">
              <div class="col col-md-6">
                <p class="copyright_text">
                  <a href="">Copyright</a> © <a href="https://gedexo.com/"><b>Gedexo</b></a> All rights reserved.
                </p>
              </div>
            </div>
          </div>
        </div>
      </footer>
      <!-- footer_section - end
      ================================================== -->

templates/partials/header.html
{% load static %}
<!-- header_section - start
      ================================================== -->
      {% if messages %}
        <div class="container mt-3 d-flex justify-content-center">
          <div class="w-100 text-center">
            {% for message in messages %}
              {% if 'success-border' in message.tags %}
                <div class="alert alert-success alert-dismissible fade show border-success" role="alert">
                  {{ message }}
                  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
              {% else %}
                <div class="alert alert-success alert-dismissible fade show" role="alert">
                  {{ message }}
                  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
              {% endif %}
            {% endfor %}
          </div>
        </div>
      {% endif %}

      <header class="header_section">
        <div class="header_middle">
          <div class="container">
            <div class="row align-items-center">
              <div class="col col-lg-3 col-5">
                <div class="brand_logo">
                  <a class="brand_link" href="{% url "product:index" %}">
                    <img src="{% static 'assets/images/logo/Odadoz (5).png' %}" alt="Getyootech - Gadgets Ecommerce Site Template">
                  </a>
                </div>
              </div>
              <div class="col col-lg-6 col-2">
                <nav class="main_menu navbar navbar-expand-lg">
                  <div class="main_menu_inner collapse navbar-collapse justify-content-center" id="main_menu_dropdown">
                    <ul class="main_menu_list ul_li">
                      <li><a href="{% url "product:index" %}">Home</a></li>
                      <li><a href="{% url "web:about" %}">About</a></li>
                      <li><a href="{% url "product:shop" %}">Shop</a></li>
                      <li><a href="{% url "web:contact" %}">Contact</a></li>
                      <li class="dropdown">
                        {% if request.user.is_authenticated %}
                        <a class="nav-link" href="#" id="shop_submenu" role="button" data-bs-toggle="dropdown" aria-expanded="false">Sign</a>
                        <ul class="dropdown-menu" aria-labelledby="shop_submenu">
                          <li><a href="{% url 'auth_logout' %}">Logout</a></li>
                          {% else %}
                          <li><a href="{% url 'auth_login' %}">Login</a></li>
                          <li><a href="{% url 'registration_register' %}">Register</a></li>
                          {% endif %}
                        </ul>
                      </li>
                    </ul>
                  </div>
                </nav>
              </div>

              <div class="col col-lg-3 col-5">
                <ul class="header_icons_group ul_li_right">
                  <li>
                    <button class="mobile_menu_btn navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#main_menu_dropdown" aria-controls="main_menu_dropdown" aria-expanded="false" aria-label="Toggle navigation">
                      <i class="fal fa-bars"></i>
                    </button>
                  </li>
                  <li>
                    <a href="{% url "order:wishlist" %}">
                      <i class="fa-regular fa-heart"></i>
                      <small class="wishlist_counter">{{ wishlist_items_count }}</small>
                    </a>
                  </li>
                  <li>
                    <a href="{% url "order:account" %}">
                      <i class="fa-regular fa-user"></i>
                    </a>
                  </li>
                </ul>
              </div>
            </div>
          </div>
        </div>

        <div class="header_bottom">
          <div class="container">
            <div class="row align-items-center">
              <div class="col col-md-3 col-6">
                <div class="allcategories_dropdown">
                  <button class="allcategories_btn" type="button" data-bs-toggle="collapse" data-bs-target="#allcategories_collapse" aria-expanded="false" aria-controls="allcategories_collapse">
                    <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="15" height="13" viewBox="0 0 15 13">
                     <image width="15" height="13" xlink:href="data:img/png;base64,iVBORw0KGgoAAAANSUhEUgAAAA8AAAANAgMAAAALcNzSAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAACVBMVEX+//3+//0AAABvRd2oAAAAAXRSTlMAQObYZgAAAAFiS0dEAmYLfGQAAAAJcEhZcwAACxIAAAsSAdLdfvwAAAAHdElNRQflBwIBIhVZ2fz2AAAAGUlEQVQI12MIDQ0NYQATaAAshEUcJgvVBgDy4QdJZv6kzwAAAABJRU5ErkJggg=="/>
                   </svg>
                    All Categories
                  </button>
                  <div class="allcategories_collapse collapse" id="allcategories_collapse">
                    <div class="card card-body">
                      <ul class="allcategories_list ul_li_block">
                        {% for category in all_categories %}
                        <li><a href="{% url 'product:shop' %}?category={{ category.slug }}"><i class="fa-duotone fa-rocket-launch"></i> {{ category.name }}</a></li>
                        {% endfor %}  
                      </ul>
                    </div>
                  </div>
                </div>
              </div>

              <div class="col col-md-6">
                <form action="{% url "product:shop" %}" method="get">
                  <div class="advance_serach">
                    <div class="form_item">
                      <input type="search" name="query" placeholder="Search Prudcts...">
                    </div>
                    <button type="submit" class="search_btn"><i class="far fa-search"></i></button>
                  </div>
                </form>
              </div>

              <div class="col col-md-3 col-6">
                <button type="button" class="cart_btn">
                  <span class="cart_icon">
                    <i class="icon icon-ShoppingCart"></i>
                    <small class="cart_counter">{{request.session.cart|length}}</small>
                  </span>
                  
                </button>
              </div>
            </div>
          </div>
        </div>
      </header>
      <!-- header_section - end
      ================================================== -->