odadoz/urls.py
# Define urlpatterns in project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views.generic import TemplateView

urlpatterns = (
    [
        path("admin/", admin.site.urls),
        path("", include("web.urls", namespace="web")),
        path("", include("product.urls", namespace="product")),
        path("", include("order.urls", namespace="order")),
        path("sitemap.xml", TemplateView.as_view(template_name="sitemap.xml", content_type="text/xml")),
        path("robots.txt", TemplateView.as_view(template_name="robots.txt", content_type="text/plain")),
        path('accounts/', include('registration.backends.simple.urls')),
    ]
    + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
)

admin.site.site_header = "PROJECT Administration"
admin.site.site_title = "PROJECT Admin Portal"
admin.site.index_title = "Welcome to PROJECT Admin Portal"

order/urls.py
from django.urls import path
from . import views
from .views import wishlist, add_to_wishlist, remove_from_wishlist

app_name = "order"

urlpatterns = [
    #cart
    path('cart/add/<int:id>/', views.cart_add, name='cart_add'),
    path('cart/item_clear/<int:id>/', views.item_clear, name='item_clear'),
    path('cart/item_increment/<int:id>/',
         views.item_increment, name='item_increment'),
    path('cart/item_decrement/<int:id>/',
         views.item_decrement, name='item_decrement'),
    path('cart/cart_clear/', views.cart_clear, name='cart_clear'),
    path('cart/cart-detail/',views.cart_detail,name='cart_detail'),
    path('checkout',views.checkout,name='checkout'),
    # wishlist
    path('wishlist/', wishlist, name='wishlist'),
    path('add_to_wishlist/<int:product_id>/', add_to_wishlist, name='add_to_wishlist'),
    path('remove_from_wishlist/<int:item_id>/', remove_from_wishlist, name='remove_from_wishlist'),
    #account 
    path("account", views.account, name="account"),
    path('order/',views.your_order,name='order'),
    #profile update
    path('profile/',views.profile,name='profile'),
    path('profile/update',views.profile_update,name='profile_update'),
]

product/urls.py
from django.urls import path
from . import views

app_name = "product"

urlpatterns = [
    path("", views.index, name="index"),
    # shop
    path("shop/", views.shop, name="shop"),
    path("shop/filter-data", views.filter_data, name="filter-data"),
    path('shop/<slug:slug>/', views.ShopDetailView.as_view(), name='shop_details'),
]

web/urls.py
from django.urls import path
from . import views

app_name = "web"

urlpatterns = [
    path("contact/", views.contact, name="contact"),
    path("about/", views.about, name="about"),
]

order/models.py
from django.db import models
from django.contrib.auth.models import User
from product.models import Product


# Create your models here.
class Order(models.Model):  
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    firstname=models.CharField(max_length=250)
    lastname=models.CharField(max_length=250)
    district=models.CharField(max_length=250)
    address=models.TextField()
    town=models.CharField(max_length=350)
    country=models.CharField(max_length=350)
    postcode=models.IntegerField()
    email=models.EmailField(max_length=350)
    telephone=models.IntegerField()

    verbose_name = "Order"
    verbose_name_plural = "Orders"


    def __str__(self):
        return self.firstname
    
class Order_Item(models.Model):
    order=models.ForeignKey(Order,on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    image=models.ImageField(upload_to='media/order_image')
    product_name = models.CharField(max_length=450) 
    price=models.FloatField()
    quantity=models.IntegerField()
    total=models.IntegerField()
    paid=models.BooleanField(default=False)

    verbose_name = "Order Item"
    verbose_name_plural = "Order Items"

    def __str__(self):
        return self.product_name
    
    
class Wishlist(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    product = models.ForeignKey("product.Product", on_delete=models.CASCADE)
    variant = models.CharField(max_length=100)
    price = models.PositiveIntegerField()

    class Meta:
        unique_together = ("user", "product")
        verbose_name = "Wishlist Item"
        verbose_name_plural = "Wishlist Items"


class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    profile_pic = models.ImageField(upload_to='profile_pics/', blank=True, null=True)
    first_name = models.CharField(max_length=30, blank=True)
    last_name = models.CharField(max_length=30, blank=True)
    bio_data = models.TextField(blank=True)
    email = models.EmailField(max_length=255, blank=True)

    def __str__(self):
        return self.user.username

order/views.py
from django.shortcuts import render, redirect
from product.models import Product
from django.contrib.auth.decorators import login_required
from cart.cart import Cart
from django.contrib.auth.models import User
from .models import Order,Order_Item
from django.contrib import messages
from django.shortcuts import get_object_or_404
from .models import Wishlist
from product.models import Category
from .models import UserProfile
from django.http import JsonResponse


# Create your views here.
@login_required(login_url="auth_login")
def cart_add(request, id):
    cart = Cart(request)
    product = Product.objects.get(id=id)
    cart.add(product=product)
    return redirect("product:index")


@login_required(login_url="auth_login")
def item_clear(request, id):
    cart = Cart(request)
    product = Product.objects.get(id=id)
    cart.remove(product)
    return redirect("order:cart_detail")


@login_required(login_url="auth_login")
def item_increment(request, id):
    cart = Cart(request)
    product = Product.objects.get(id=id)
    cart.add(product=product)
    return redirect("order:cart_detail")


@login_required(login_url="auth_login")
def item_decrement(request, id):
    cart = Cart(request)
    product = Product.objects.get(id=id)
    cart.decrement(product=product)
    return redirect("order:cart_detail")


@login_required(login_url="auth_login")
def cart_clear(request):
    cart = Cart(request)
    cart.clear()
    return redirect("order:cart_detail")


@login_required(login_url="auth_login")
def cart_detail(request):
    wishlist_items = Wishlist.objects.filter(user=request.user)
    wishlist_items_count = wishlist_items.count()

    context = {
        'wishlist_items_count': wishlist_items_count,
        'all_categories': Category.objects.all(),
    }
    return render(request, 'cart/cart.html', context)


@login_required(login_url="auth_login")
def checkout(request):
    if request.method == "POST":
        uid = request.session.get('_auth_user_id')
        user = User.objects.get(id=uid)
        cart = request.session.get('cart')

        firstname = request.POST.get('firstname')
        lastname = request.POST.get('lastname')
        district = request.POST.get('district')
        address = request.POST.get('streetaddress')
        town = request.POST.get('town')
        country = request.POST.get('country')
        postcode = request.POST.get('postcode')
        email = request.POST.get('email')
        telephone = request.POST.get('telephone')

        if any(field is None for field in [firstname, lastname, district, address, town, country, postcode, email, telephone]):
            messages.error(request, "Please fill in all the required fields.")
            return redirect('product:index')

        order_1 = Order(
            user=user,
            firstname=firstname,
            lastname=lastname,
            district=district,
            address=address,
            town=town,
            country=country,
            postcode=postcode,
            email=email,
            telephone=telephone,
        )
        order_1.save()

        for i in cart:
            a = float(cart[i]['price'])
            b = int(cart[i]['quantity'])
            total = a * b

            product_name = cart[i]['name']
            product = Product.objects.get(name=product_name)
            order_item = Order_Item(
                order=order_1,
                product=product,  
                product_name=product_name,
                image=product.image, 
                price=cart[i]['price'],
                quantity=cart[i]['quantity'],
                total=total
            )
            order_item.save()

        request.session['cart'] = {}
        messages.success(request, "Order placed successfully!")
        return redirect("product:index")
    
    wishlist_items = Wishlist.objects.filter(user=request.user)
    wishlist_items_count = wishlist_items.count()
    
    context = {
        'wishlist_items': wishlist_items,
        'wishlist_items_count': wishlist_items_count,
        'all_categories': Category.objects.all(),
    }
    return render(request, 'checkout/checkout.html', context)


@login_required(login_url="auth_login")
def your_order(request):
    wishlist_items = Wishlist.objects.filter(user=request.user)
    wishlist_items_count = wishlist_items.count()

    if request.user.is_authenticated:
        uid = request.user.id
        user = User.objects.get(id=uid)
        orders = Order.objects.filter(user=user)
        order_items = Order_Item.objects.filter(order__in=orders)
    else:
        order_items = []

    context = {
        'order_items': order_items,
        'all_categories': Category.objects.all(),
        'wishlist_items_count': wishlist_items_count,
        'wishlist_items': wishlist_items,
    }
    return render(request, 'order.html', context)


@login_required(login_url="auth_login")
def wishlist(request):
    wishlist_items = Wishlist.objects.filter(user=request.user)
    wishlist_items_count = wishlist_items.count()

    context = {
        'wishlist_items': wishlist_items,
        'wishlist_items_count': wishlist_items_count,
        'all_categories': Category.objects.all(),
    }
    return render(request, 'wishlist.html', context)


@login_required(login_url="auth_login")
def add_to_wishlist(request, product_id):
    product = get_object_or_404(Product, id=product_id)

    if not Wishlist.objects.filter(user=request.user, product=product).exists():
        wishlist_item = Wishlist(user=request.user, product=product, price=product.price)
        wishlist_item.save()
        messages.success(request, f"Item added to your wishlist successfully!")
    else:
        messages.info(request, f"Item is already in your wishlist.")

    if request.is_ajax():
        return JsonResponse({'message': 'Item added to wishlist successfully'})

    return redirect("product:index")



@login_required(login_url="auth_login")
def remove_from_wishlist(request, item_id):
    wishlist_item = get_object_or_404(Wishlist, id=item_id)

    if wishlist_item.user == request.user:
        wishlist_item.delete()
        messages.success(request, f"removed from your wishlist!")
    else:
        messages.error(request, "You are not authorized to remove this item from the wishlist.")

    return redirect("order:wishlist")


@login_required(login_url="auth_login")
def account(request):
    wishlist_items = Wishlist.objects.filter(user=request.user)
    wishlist_items_count = wishlist_items.count()

    context = {
        'wishlist_items': wishlist_items,
        'wishlist_items_count': wishlist_items_count,
        'all_categories': Category.objects.all(),
    }
    return render(request, 'account.html', context)


@login_required(login_url="auth_login")
def profile(request):
    try:
        user_profile = request.user.userprofile
    except UserProfile.DoesNotExist:
        user_profile = UserProfile(user=request.user)
        user_profile.save()
    wishlist_items = Wishlist.objects.filter(user=request.user)
    wishlist_items_count = wishlist_items.count()


    context = {
        'user_profile': user_profile,
        'wishlist_items': wishlist_items,
        'wishlist_items_count': wishlist_items_count,
    }
    return render(request, 'profile.html', context)


@login_required(login_url="auth_login")
def profile_update(request):
    try:
        user_profile = request.user.userprofile
    except UserProfile.DoesNotExist:
        user_profile = UserProfile(user=request.user)
        user_profile.save()

    if request.method == 'POST':
        # Update other fields
        user_profile.first_name = request.POST.get('first_name', '')
        user_profile.last_name = request.POST.get('last_name', '')
        user_profile.bio_data = request.POST.get('bio_data', '')
        user_profile.email = request.POST.get('email', '')

        profile_pic = request.FILES.get('profile_pic')
        if profile_pic:
            user_profile.profile_pic = profile_pic

        user_profile.save()
        messages.success(request, 'Profile updated successfully!')
        return redirect('order:profile')

    context = {
        'user_profile': user_profile,
    }

    return render(request, 'profile.html', context)

templates/account.html
{% extends "partials/base.html" %}
{% load static %}
{% load product_tags %}
{% block title %} Account {% endblock  %}
{% block content %}
    <!-- body_wrap - start -->
    <div class="body_wrap">

      <!-- backtotop - start -->
      <div class="backtotop">
        <a href="javascript:void(0)" class="scroll">
          <i class="far fa-arrow-up"></i>
        </a>
      </div>
      <!-- backtotop - end -->

      <!-- main body - start
      ================================================== -->
      <main>

        <!-- sidebar cart - start
        ================================================== -->
        <div class="sidebar-menu-wrapper">
          <div class="cart_sidebar">
            <button type="button" class="close_btn"><i class="fal fa-times"></i></button>

            <ul class="cart_items_list ul_li_block mb_30 clearfix">
              {% for key,value in request.session.cart.items %}
              <li>
                <div class="item_image">
                  <img src="{{value.image}}" alt="Getyootech - Gadgets Ecommerce Site Template">
                </div>
                <div class="item_content">
                  <h4 class="item_title">{{value.name}}</h4>
                  <span class="item_price">${{value.price}}</span>
                </div>
                <a href="{% url "order:item_clear" key %}"><button type="button" class="remove_btn"><i class="fal fa-trash-alt"></i></button></a>
              </li>
              {% endfor %}
            </ul>

            <ul class="total_price ul_li_block mb_30 clearfix">
              <li>
                <span>Subtotal:</span>
                <span>${{cart_total_amount}}</span>
              </li>
              <li>
                <span>Vat 5%:</span>
                <span>$4.5</span>
              </li>
              <li>
                <span>Discount 20%:</span>
                <span>- $18.9</span>
              </li>
              <li>
                <span>Total:</span>
                <span>${{cart_total_amount}}</span>
              </li>
            </ul>

            <ul class="btns_group ul_li_block clearfix">
              <li><a class="btn btn_primary" href="{% url "order:cart_detail" %}">View Cart</a></li>
              <li><a class="btn btn_secondary" href="{% url "order:checkout" %}">Checkout</a></li>
            </ul>
          </div>

          <div class="cart_overlay"></div>
        </div>
        <!-- sidebar cart - end
        ================================================== -->

        <!-- breadcrumb_section - start
        ================================================== -->
        <div class="breadcrumb_section">
          <div class="container">
            <ul class="breadcrumb_nav ul_li">
              <li><a href="{% url "product:index" %}">Home</a></li>
              <li>My Account</li>
            </ul>
          </div>
        </div>
        <!-- breadcrumb_section - end
        ================================================== -->

        <!-- account_section - start
        ================================================== -->
        <section class="account_section section_space">
          <div class="container">
            <div class="row">
              <div class="col col-lg-3">
                <div class="account_menu">
                  <h2 class="title_text">My Account</h2>
                  <ul class="account_menu_list ul_li_block">
                    <li class="active"><a href="javascript:void(0)">Account Dashboard</a></li>
                    <li><a href="{% url "order:order" %}" class="align-items-center d-flex">My Orders<i class="fa-solid fa-box-archive ms-auto"></i></a></li>
                    <li><a href="{% url "order:wishlist" %}" class="align-items-center d-flex">My Wishlist<i class="fa-solid fa-heart ms-auto"></i></a></li>
                    <li><a href="{% url 'auth_logout' %}" class="align-items-center d-flex">Logout<i class="fa-solid fa-right-from-bracket ms-auto"></i></a></li>
                  </ul>
                </div>
              </div>

              <div class="col col-lg-9">
                <div class="account_content_area">
                  <h3>My Dashboard</h3>
                  <ul class="content_layout ul_li_block">
                    <li>
                     
                          <img src="{{ request.user.userprofile.profile_pic.url }}" alt="Profile Picture" class="rounded-circle" style="width:50px; height:50px;">
                   
                      <h4 class="mt-2"><strong>{{request.user.userprofile.first_name}}, {{request.user.userprofile.last_name}}!</strong></h4>
                      <p class="mb-0">
                        Explore your Dashboard's power. Easily manage account details, gain insights into recent activity, and take control. Select a link below to view or edit your information.
                      <div>
                        <a href="{% url "order:profile" %}"><button class="btn btn-danger mt-2">update profile</button></a>
                      </div>
                    </li>
                    <li>
                      <h4>Contact Information</h4>
                      <p class="mb-0">
                        {{request.user.username}}
                      </p>
                      <a class="mb-3" href="javascript:void(0)">{{request.user.email}}</a>
                      <ul class="btns_group ul_li">
                        <li><a class="btn btn_gray" href="javascript:void(0)">Edit Account Information</a></li>
                        <li><a class="btn btn_gray" href="{% url 'auth_password_change' %}">Change Password</a></li>
                      </ul>
                    </li>
                  </ul>
                </div>
              </div>
            </div>
          </div>
        </section>
        <!-- account_section - end
        ================================================== -->

        <!-- newsletter_section - start
        ================================================== -->
        <section class="newsletter_section">
          <div class="container">
            <div class="row align-items-center">
              <div class="col col-lg-6">
                <h2 class="newsletter_title text-white">
                  <i class="icofont-paper-plane"></i>
                  Sign Up for Newsletter
                </h2>
              </div>
              <div class="col col-lg-6">
                <form action="javascript:void(0)">
                  <div class="newsletter_form">
                    <input type="email" name="email" placeholder="Enter your email address">
                    <button type="submit" class="btn btn_danger">Submit</button>
                  </div>
                </form>
              </div>
            </div>
          </div>
        </section>
        <!-- newsletter_section - end
        ================================================== -->

      </main>
      <!-- main body - end
      ================================================== -->

    </div>
    <!-- body_wrap - end -->
{% endblock  %}

templates/profile.html
{% extends "partials/base.html" %}
{% load static %}
{% load product_tags %}
{% block title %} Profile {% endblock  %}
{% block content %}
      <!-- sidebar cart - start
        ================================================== -->
        <div class="sidebar-menu-wrapper">
          <div class="cart_sidebar">
            <button type="button" class="close_btn"><i class="fal fa-times"></i></button>

            <ul class="cart_items_list ul_li_block mb_30 clearfix">
              {% for key,value in request.session.cart.items %}
              <li>
                <div class="item_image">
                  <img src="{{value.image}}" alt="Getyootech - Gadgets Ecommerce Site Template">
                </div>
                <div class="item_content">
                  <h4 class="item_title">{{value.name}}</h4>
                  <span class="item_price">${{value.price}}</span>
                </div>
                <a href="{% url "order:item_clear" key %}"><button type="button" class="remove_btn"><i class="fal fa-trash-alt"></i></button></a>
              </li>
              {% endfor %}
            </ul>

            <ul class="total_price ul_li_block mb_30 clearfix">
              <li>
                <span>Subtotal:</span>
                <span>${{cart_total_amount}}</span>
              </li>
              <li>
                <span>Vat 5%:</span>
                <span>$4.5</span>
              </li>
              <li>
                <span>Discount 20%:</span>
                <span>- $18.9</span>
              </li>
              <li>
                <span>Total:</span>
                <span>${{cart_total_amount}}</span>
              </li>
            </ul>

            <ul class="btns_group ul_li_block clearfix">
              <li><a class="btn btn_primary" href="{% url "order:cart_detail" %}">View Cart</a></li>
              <li><a class="btn btn_secondary" href="{% url "order:checkout" %}">Checkout</a></li>
            </ul>
          </div>

          <div class="cart_overlay"></div>
        </div>
        <!-- sidebar cart - end
        ================================================== -->

        <div class="container mt-5">
            <h5>Profile Update</h5>
            <form method="post" action="{% url 'order:profile_update' %}" enctype="multipart/form-data">
                {% csrf_token %}
            <div class="mb-3 mt-4">
                <label for="exampleInputName" class="form-label">Profile Pic</label>
                <input type="file" class="form-control" id="exampleInputName" name="profile_pic">
            </div>
              <div class="mb-3">
                <label for="exampleInputName" class="form-label">First Name</label>
                <input type="text" class="form-control" id="exampleInputName" name="first_name" value="{{request.user.userprofile.first_name}}">
              </div>
              <div class="mb-3">
                <label for="exampleInputName" class="form-label">Last Name</label>
                <input type="text" class="form-control" id="exampleInputName" name="last_name" value="{{request.user.userprofile.last_name}}">
              </div>
              <div class="mb-3">
                <label for="exampleInputName" class="form-label">Username</label>
                <input type="text" class="form-control" id="exampleInputName" name="username" value="{{request.user.username}}">
              </div>
              <div class="mb-3">
                <label for="exampleInputEmail" class="form-label">admin</label>
                <input type="text" class="form-control" id="exampleInputEmail" aria-describedby="emailHelp" name="bio_data" value="{{request.user.admin}}">
              </div>
              <div class="mb-3">
                <label for="exampleInputEmail" class="form-label">Email</label>
                <input type="email" class="form-control" id="exampleInputEmail" aria-describedby="emailHelp" name="email" value="{{request.user.email}}">
              </div>
              <button type="submit" class="btn btn-danger">Update Profile</button>
            </form>
          </div>
{% endblock  %}

templates/wishlist.html
{% extends "partials/base.html" %}
{% load static %}
{% load product_tags %}
{% block title %} Wishlist {% endblock  %}
{% block content %}
    <!-- body_wrap - start -->
    <div class="body_wrap">

      <!-- backtotop - start -->
      <div class="backtotop">
        <a href="javascript:void(0)" class="scroll">
          <i class="far fa-arrow-up"></i>
        </a>
      </div>
      <!-- backtotop - end -->

      <!-- main body - start
      ================================================== -->
      <main>

        <!-- sidebar cart - start
        ================================================== -->
        <div class="sidebar-menu-wrapper">
          <div class="cart_sidebar">
            <button type="button" class="close_btn"><i class="fal fa-times"></i></button>

            <ul class="cart_items_list ul_li_block mb_30 clearfix">
              {% for key,value in request.session.cart.items %}
              <li>
                <div class="item_image">
                  <img src="{{value.image}}" alt="Getyootech - Gadgets Ecommerce Site Template">
                </div>
                <div class="item_content">
                  <h4 class="item_title">{{value.name}}</h4>
                  <span class="item_price">${{value.price}}</span>
                </div>
                <a href="{% url "order:item_clear" key %}"><button type="button" class="remove_btn"><i class="fal fa-trash-alt"></i></button></a>
              </li>
              {% endfor %}
            </ul>

            <ul class="total_price ul_li_block mb_30 clearfix">
              <li>
                <span>Subtotal:</span>
                <span>${{cart_total_amount}}</span>
              </li>
              <li>
                <span>Vat 5%:</span>
                <span>$4.5</span>
              </li>
              <li>
                <span>Discount 20%:</span>
                <span>- $18.9</span>
              </li>
              <li>
                <span>Total:</span>
                <span>${{cart_total_amount}}</span>
              </li>
            </ul>

            <ul class="btns_group ul_li_block clearfix">
              <li><a class="btn btn_primary" href="{% url "order:cart_detail" %}">View Cart</a></li>
              <li><a class="btn btn_secondary" href="{% url "order:checkout" %}">Checkout</a></li>
            </ul>
          </div>

          <div class="cart_overlay"></div>
        </div>
        <!-- sidebar cart - end
        ================================================== -->

        <!-- breadcrumb_section - start
        ================================================== -->
        <div class="breadcrumb_section">
          <div class="container">
            <ul class="breadcrumb_nav ul_li">
              <li><a href="{% url "product:index" %}">Home</a></li>
              <li>Wishlist</li>
            </ul>
          </div>
        </div>
        <!-- breadcrumb_section - end
        ================================================== -->

        <!-- cart_section - start
        ================================================== -->
        <section class="cart_section section_space">
          <div class="container">
            <div class="cart_table">
              <table class="table mb-0">
                <thead>
                  <tr>
                    <th>PRODUCT</th>
                    <th class="text-center">PRICE</th>
                    <th class="text-center">STOCK STATUS</th>
                    <th class="text-center">ADD TO CART</th>
                    <th class="text-center">REMOVE</th>
                  </tr>
                </thead>
                <tbody>
                  {% for item in wishlist_items %}
                  <tr>
                    <td>
                      <div class="cart_product">
                        <img src="{{item.product.image.url}}" alt="Getyootech - Gadgets Ecommerce Site Template">
                        <h3></h3>
                      </div>
                    </td>
                    <td class="text-center">
                      <span class="price_text">₹ {% call_sellprice item.product.price item.product.discount %}</span>
                    </td>
                    <td class="text-center"><span class="price_text text-success">In Stock</span></td>
                    <td class="text-center">
                      <a href="{% url 'order:cart_add' id=item.product.id %}" class="btn btn_gray">Add To Cart</a>
                    </td>
                    <td class="text-center"><a href="{% url 'order:remove_from_wishlist' item_id=item.id %}"><button type="button" class="remove_btn"><i class="fal fa-trash-alt"></i></button></td></a>
                  </tr>
                  {% endfor %}
                </tbody>
              </table>
            </div>
          </div>
        </section>
        <!-- cart_section - end
        ================================================== -->

        <!-- newsletter_section - start
        ================================================== -->
        <section class="newsletter_section">
          <div class="container">
            <div class="row align-items-center">
              <div class="col col-lg-6">
                <h2 class="newsletter_title text-white">
                  <i class="icofont-paper-plane"></i>
                  Sign Up for Newsletter
                </h2>
              </div>
              <div class="col col-lg-6">
                <form action="javascript:void(0)">
                  <div class="newsletter_form">
                    <input type="email" name="email" placeholder="Enter your email address">
                    <button type="submit" class="btn btn_danger">Submit</button>
                  </div>
                </form>
              </div>
            </div>
          </div>
        </section>
        <!-- newsletter_section - end
        ================================================== -->

      </main>
      <!-- main body - end
      ================================================== -->

    </div>
    <!-- body_wrap - end -->
{% endblock  %}